insert into sentences (text) values
  ('The quick brown fox jumps over the lazy dog near the riverbank.'),
  ('Programming is the art of telling another human what one wants the computer to do.'),
  ('A journey of a thousand miles begins with a single step forward.'),
  ('The only way to do great work is to love what you do every single day.'),
  ('In the middle of every difficulty lies opportunity waiting to be discovered.'),
  ('The best time to plant a tree was twenty years ago, the second best time is now.'),
  ('Success is not final, failure is not fatal, it is the courage to continue that counts.'),
  ('You miss one hundred percent of the shots you do not take in life.'),
  ('Whether you think you can or you think you cannot, you are right about it.'),
  ('The purpose of our lives is to be happy and to make others feel happy too.'),
  ('Life is what happens when you are busy making other plans for the future.'),
  ('Get busy living or get busy dying, there is no other way around it.'),
  ('You only live once, but if you do it right, once is more than enough.'),
  ('To be yourself in a world that is constantly trying to make you something else is an achievement.'),
  ('In three words I can sum up everything I have learned about life: it goes on.'),
  ('If you want to live a happy life, tie it to a goal, not to people or objects.'),
  ('Never let the fear of striking out keep you from playing the game of life.'),
  ('Money and success do not change people, they merely amplify what is already there.'),
  ('Your time is limited, so do not waste it living someone else''s life out there.'),
  ('Not how long, but how well you have lived is the main thing in life.');
